# Generated by Django 5.2 on 2025-04-23 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excavator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExcavatorPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('latitude_deg', models.FloatField()),
                ('latitude_min', models.FloatField()),
                ('longitude_deg', models.FloatField()),
                ('longitude_min', models.FloatField()),
                ('altitude', models.FloatField()),
                ('satellites', models.IntegerField()),
                ('fix_quality', models.IntegerField()),
                ('excavator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='server.excavator')),
            ],
        ),
    ]
